#Name of action
name: jekyll CI

#This makes the action trigger on any push to the master branch of the repository
on:
  push:
    branches: [ main ]
#They will be executed in order in an Ubuntu environment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 1   
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
            source-files: './_site'
            destination-username: 'teach9372'
            destination-repository: 'teach9372.github.io'
            destination-directory: ''
