#Name of action
name: jekyll CI

#This makes the action trigger on any push to the master branch of the repository
on:
  push:
    branches: [ main ]
#They will be executed in order in an Ubuntu environment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #This task checks out the git repository so it can be used by your action
      - uses: actions/checkout@v2
      #This task pushes the build to the Front_End repository
       - name: Push generated webpage to another repository
          uses: nkoppel/push-files-to-another-repository@1.1.0
          env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          with:
            source-files: './_site'
            destination-username: 'teach9372'
            destination-repository: 'teach9372.github.io'
            destination-directory: ''
            commit-email: 'murgucal@gmail.com"
